services:
  kafka:
    image: confluentinc/cp-kafka:8.0.3
    container_name: kafka
    environment:
      CLUSTER_ID: fraud-detection
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
    ports:
      - 9092:9092

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: debezium
      POSTGRES_PASSWORD: dbz
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  connect:
    image: debezium/connect:2.7.3.Final
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets


volumes:
  postgres_data: