spring:
  application:
    name: fraud-detection
  datasource:
    url: jdbc:postgresql://localhost:5433/transactions_db
    username: debezium
    password: dbz
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
